// Code generated by yalb.aero/api. DO NOT EDIT.
//
// Regenerate with: go run ./cmd/aero contract > frontend/src/api/contract.ts
// TestGeneratedTypeScriptMatchesTheCheckedInFile fails when this file drifts
// from the Go types that define the contract.
//
// These are types, not validation. They describe what a response is expected to
// look like and vanish at run time; they do not check that an untrusted body
// has that shape. Validate a decoded response before trusting it.

export const CONTRACT_VERSION = "v1";

export type AreaBasis =
  "reference-trapezoid" |
  "exposed-panels";

export type BoundDirection =
  "minimum" |
  "maximum";

export type CaseScope =
  "all-required" |
  "single";

export type CoefficientScope =
  "aircraft" |
  "airfoil-section";

export type CommandKind =
  "promote-driver" |
  "remove-case" |
  "remove-requirement" |
  "set-case" |
  "set-case-clmax" |
  "set-case-priority" |
  "set-driver" |
  "set-mass" |
  "set-requirement" |
  "set-requirement-priority" |
  "set-taper-ratio" |
  "size-at-stall-limit";

export type Configuration =
  "conventional-tail" |
  "v-tail" |
  "flying-wing";

export type DihedralMode =
  "hold-panel" |
  "hold-projected";

export type Dimension =
  "ratio" |
  "mass" |
  "force" |
  "length" |
  "area" |
  "speed" |
  "density" |
  "force-per-area" |
  "mass-per-area" |
  "angle" |
  "power" |
  "energy" |
  "dynamic-viscosity";

export type DriverKey =
  "wing.span.projected" |
  "wing.span.panel" |
  "wing.area.reference" |
  "wing.area.panel" |
  "wing.aspect_ratio.planform" |
  "wing.chord.root";

export type Evidence =
  "assumed" |
  "measured" |
  "simulated";

export type IssueKind =
  "missing" |
  "invalid" |
  "unsupported";

export type Journey =
  "span-first" |
  "mass-and-performance-first" |
  "mass-and-size-first" |
  "existing-design" |
  "power-first";

export type ParameterRole =
  "driver" |
  "derived";

export type PlanformShape =
  "rectangle" |
  "trapezoid";

export type Priority =
  "required" |
  "preferred";

export type RequirementStatus =
  "unknown" |
  "met" |
  "unmet";

export type RequirementSubject =
  "stall-speed" |
  "wing-area" |
  "span" |
  "mass" |
  "aspect-ratio" |
  "mass-wing-loading";

export type ResultStatus =
  "missing" |
  "computed" |
  "invalid" |
  "stale";

export type SolveMode =
  "span-and-area" |
  "span-and-aspect-ratio" |
  "area-and-aspect-ratio" |
  "span-and-root-chord" |
  "area-and-root-chord" |
  "aspect-ratio-and-root-chord";

export type SourceKind =
  "book" |
  "supplementary" |
  "derived";

export interface Discovery {
  contractVersion: string;
  version: string;
  equations: Equation[];
  patterns: Pattern[];
  units: UnitInfo[];
  vocabularies: Vocabulary[];
  limits: Limits;
}

export interface Limits {
  maxCases: number;
  maxRequirements: number;
  maxCommands: number;
  maxBatch: number;
  maxRequestBytes: number;
}

export interface Vocabulary {
  name: string;
  tokens: string[];
}

export interface UnitInfo {
  symbol: string;
  dimension: string;
  si: boolean;
}

export interface Equation {
  id: string;
  revision: string;
  expression: string;
  inputs: Port[];
  output: Port;
  assumptions: string[];
  source: Source;
}

export interface Port {
  name: string;
  description: string;
  dimension: string;
  unit: string;
}

export interface Source {
  kind: string;
  title: string;
  url: string;
  section: string;
  accessed: string;
  upstreamRevision?: string;
  originalUnits: string;
  adaptation: string;
}

export interface Pattern {
  id: string;
  name: string;
  journey: string;
  rationale: string;
  outcome: string;
  requiredInputs: string[];
  activeDrivers: string[];
  validityLimits: string[];
  supported: boolean;
}

export interface EvaluateRequest {
  request: Request;
  design: Design;
}

export interface BatchEvaluateRequest {
  evaluations: EvaluateRequest[];
}

export interface BatchEvaluateResponse {
  evaluations: Evaluation[];
}

export interface ApplyRequest {
  request: Request;
  design: Design;
  commands: Command[];
}

export interface ApplyResponse {
  applied: string[];
  design: Design;
  evaluation: Evaluation;
}

export interface PreviewRequest {
  request: Request;
  design: Design;
  command: Command;
}

export interface PreviewResponse {
  command: string;
  before: Evaluation;
  after: Evaluation;
  changes: Change[];
}

export interface Evaluation {
  request: Request;
  snapshot: string;
  geometry: string;
  aggregate: string;
  wing?: SolvedWing | null;
  checks: Check[];
  areaLower: Bound;
  areaUpper: Bound;
  mass: MassRange;
  conflicts: Conflict[];
  patterns: string[];
  definitionIssues: Issue[];
  geometryIssues: Issue[];
  configurationIssues: Issue[];
  hasRequired: boolean;
}

export interface Design {
  name: string;
  configuration: string;
  massBasis: string;
  mass?: Quantity | null;
  wing: Wing;
  tail?: Tail | null;
  cases?: Case[];
  requirements?: Requirement[];
}

export interface Wing {
  name: string;
  shape: string;
  span?: Quantity | null;
  area?: Quantity | null;
  rootChord?: Quantity | null;
  aspectRatio: number;
  taperRatio: number;
  sweep?: Quantity | null;
  dihedral?: Quantity | null;
  twist?: Quantity | null;
  incidence?: Quantity | null;
  bodyWidth?: Quantity | null;
  sweepReference: number;
  areaBasis: string;
  dihedralMode?: string;
  rootAirfoil?: Airfoil | null;
  tipAirfoil?: Airfoil | null;
}

export interface Airfoil {
  designation: string;
  evidence: string;
  thicknessRatio: number;
}

export interface Tail {
  horizontal?: Surface | null;
  vertical?: Surface | null;
  vtail?: VTail | null;
}

export interface Surface {
  area?: Quantity | null;
  span?: Quantity | null;
  arm?: Quantity | null;
}

export interface VTail {
  panelArea?: Quantity | null;
  panelSpan?: Quantity | null;
  cant?: Quantity | null;
  arm?: Quantity | null;
}

export interface Case {
  name: string;
  configuration: string;
  densityBasis: string;
  viscosityBasis?: string;
  priority: string;
  density?: Quantity | null;
  viscosity?: Quantity | null;
  clmax: CLmax;
  loadFactor: number;
}

export interface CLmax {
  scope: string;
  basis: string;
  evidence?: string;
  max: number;
}

export interface Requirement {
  name: string;
  subject: string;
  priority: string;
  basis: string;
  cases?: string[];
  minimum?: Quantity | null;
  maximum?: Quantity | null;
  margin: number;
}

export interface Command {
  kind: string;
  basis?: string;
  key?: string;
  promote?: string;
  release?: string;
  name?: string;
  priority?: string;
  hold?: string;
  mass?: Quantity | null;
  value?: Quantity | null;
  requirement?: Requirement | null;
  case?: Case | null;
  clmax?: CLmax | null;
  scope?: Scope | null;
  ratio?: number;
}

export interface Scope {
  kind: string;
  case?: string;
}

export interface SolvedWing {
  datum: string;
  solveMode: string;
  drivers: string[];
  parameters: Parameter[];
  outline: Point[];
}

export interface Parameter {
  key: string;
  role: string;
  datum?: string;
  equationId?: string;
  revision?: string;
  dependsOn?: string[];
  value: Quantity;
}

export interface Point {
  x: Quantity;
  y: Quantity;
  z: Quantity;
}

export interface Check {
  name: string;
  case?: string;
  subject: string;
  direction: string;
  priority: string;
  status: string;
  result: string;
  evidence?: string;
  detail?: string;
  bound: Quantity;
  actual?: Quantity | null;
  trace?: Trace | null;
  margin: number;
}

export interface Bound {
  subject: string;
  direction: string;
  detail?: string;
  controlling?: string[];
  contributions?: Contribution[];
  value?: Quantity | null;
  known: boolean;
  partial: boolean;
}

export interface Contribution {
  source: string;
  detail?: string;
  value?: Quantity | null;
  trace?: Trace | null;
  known: boolean;
}

export interface MassRange {
  detail?: string;
  lower: Bound;
  upper: Bound;
  complete: boolean;
  empty: boolean;
}

export interface Conflict {
  summary: string;
  detail: string;
  group: string[];
  alternatives: Alternative[];
}

export interface Alternative {
  name: string;
  description: string;
  command: Command;
}

export interface Change {
  name: string;
  case?: string;
  subject: string;
  direction: string;
  from: string;
  to: string;
  detail: string;
  appeared: boolean;
  vanished: boolean;
}

export interface Trace {
  equationId: string;
  revision: string;
  expression: string;
  substitutions: Substitution[];
  result: Quantity;
}

export interface Substitution {
  name: string;
  value: Quantity;
}

export interface Quantity {
  unit: string;
  value: number;
}

export interface Issue {
  field: string;
  kind: string;
  detail: string;
}

export interface Request {
  session: string;
  sequence: number;
}
