// Code generated by yalb.aero/api. DO NOT EDIT.
//
// Regenerate with: go run ./cmd/aero contract > frontend/src/api/contract.ts
// TestGeneratedTypeScriptMatchesTheCheckedInFile fails when this file drifts
// from the Go types that define the contract.
//
// These are types, not validation. They describe what a response is expected to
// look like and vanish at run time; they do not check that an untrusted body
// has that shape. Validate a decoded response before trusting it.

export const CONTRACT_VERSION = "v1";

export type AreaBasis =
  "reference-trapezoid" |
  "exposed-panels";

export type BatteryEnergyMode =
  "capacity-and-voltage" |
  "entered-energy";

export type BoundDirection =
  "minimum" |
  "maximum";

export type CapabilityKind =
  "static" |
  "in-flight";

export type CaseScope =
  "all-required" |
  "single";

export type CoefficientScope =
  "aircraft" |
  "airfoil-section";

export type CommandKind =
  "move-mission-segment" |
  "place-component" |
  "promote-driver" |
  "remove-auxiliary-load" |
  "remove-capability" |
  "remove-case" |
  "remove-component" |
  "remove-mission-segment" |
  "remove-requirement" |
  "remove-thrust-target" |
  "set-auxiliary-load" |
  "set-battery" |
  "set-body-width" |
  "set-capability" |
  "set-case" |
  "set-case-clmax" |
  "set-case-priority" |
  "set-component" |
  "set-configuration" |
  "set-drag-polar" |
  "set-driver" |
  "set-mass" |
  "set-mass-mode" |
  "set-mission-profile" |
  "set-mission-segment" |
  "set-planform-shape" |
  "set-propulsion-efficiency" |
  "set-propulsion-limits" |
  "set-requirement" |
  "set-requirement-priority" |
  "set-taper-ratio" |
  "set-thrust-target" |
  "set-wing-angles" |
  "size-at-stall-limit";

export type ComponentRole =
  "airframe" |
  "battery" |
  "motor" |
  "avionics" |
  "payload" |
  "other";

export type Configuration =
  "conventional-tail" |
  "v-tail" |
  "flying-wing";

export type DihedralMode =
  "hold-panel" |
  "hold-projected";

export type Dimension =
  "ratio" |
  "mass" |
  "force" |
  "length" |
  "area" |
  "speed" |
  "density" |
  "force-per-area" |
  "mass-per-area" |
  "angle" |
  "power" |
  "energy" |
  "dynamic-viscosity" |
  "mass-moment" |
  "time" |
  "current" |
  "voltage" |
  "charge" |
  "rotation-rate";

export type DimensionKind =
  "linear" |
  "angular";

export type DriverKey =
  "wing.span.projected" |
  "wing.span.panel" |
  "wing.area.reference" |
  "wing.area.panel" |
  "wing.aspect_ratio.planform" |
  "wing.chord.root";

export type Evidence =
  "assumed" |
  "measured" |
  "simulated";

export type IssueKind =
  "missing" |
  "invalid" |
  "unsupported";

export type Journey =
  "span-first" |
  "mass-and-performance-first" |
  "mass-and-size-first" |
  "existing-design" |
  "power-first";

export type MassMode =
  "entered" |
  "components";

export type OutlinePlane =
  "plan-view" |
  "panel-surface";

export type ParameterRole =
  "driver" |
  "derived";

export type PlanformShape =
  "rectangle" |
  "trapezoid";

export type Priority =
  "required" |
  "preferred";

export type RegulatorSide =
  "pack-side" |
  "load-side";

export type RequirementStatus =
  "unknown" |
  "met" |
  "unmet";

export type RequirementSubject =
  "stall-speed" |
  "wing-area" |
  "span" |
  "mass" |
  "aspect-ratio" |
  "mass-wing-loading" |
  "electrical-power" |
  "mission-energy" |
  "mission-duration" |
  "mission-range" |
  "propeller-clearance";

export type ResultStatus =
  "missing" |
  "computed" |
  "invalid" |
  "stale";

export type SegmentKind =
  "launch" |
  "climb" |
  "cruise" |
  "loiter" |
  "return" |
  "recovery" |
  "other";

export type SegmentModel =
  "drag-polar" |
  "entered-estimate";

export type SegmentTiming =
  "duration" |
  "ground-distance";

export type SketchRole =
  "outline" |
  "centerline" |
  "axis" |
  "construction" |
  "reference";

export type SolveMode =
  "span-and-area" |
  "span-and-aspect-ratio" |
  "area-and-aspect-ratio" |
  "span-and-root-chord" |
  "area-and-root-chord" |
  "aspect-ratio-and-root-chord";

export type SourceKind =
  "book" |
  "supplementary" |
  "derived";

export type SweepDriverKey =
  "design.mass" |
  "wing.span.projected" |
  "wing.span.panel" |
  "wing.area.reference" |
  "wing.area.panel" |
  "wing.aspect_ratio.planform" |
  "wing.chord.root";

export type ViewKind =
  "plan-view" |
  "front-view" |
  "side-view";

export interface Discovery {
  contractVersion: string;
  version: string;
  equations: Equation[];
  patterns: Pattern[];
  units: UnitInfo[];
  vocabularies: Vocabulary[];
  limits: Limits;
}

export interface Limits {
  maxCases: number;
  maxRequirements: number;
  maxCommands: number;
  maxBatch: number;
  maxComponents: number;
  maxSweepSamples: number;
  maxCapabilities: number;
  maxThrustTargets: number;
  maxAuxiliaryLoads: number;
  maxMissionSegments: number;
  maxRequestBytes: number;
}

export interface Vocabulary {
  name: string;
  tokens: string[];
}

export interface UnitInfo {
  symbol: string;
  dimension: string;
  factorToSi: number;
  si: boolean;
}

export interface Equation {
  id: string;
  revision: string;
  expression: string;
  source: Source;
  output: Port;
  inputs: Port[];
  assumptions: string[];
}

export interface Port {
  name: string;
  description: string;
  dimension: string;
  unit: string;
}

export interface Source {
  kind: string;
  title: string;
  url: string;
  section: string;
  accessed: string;
  upstreamRevision?: string;
  originalUnits: string;
  adaptation: string;
}

export interface Pattern {
  id: string;
  name: string;
  journey: string;
  rationale: string;
  outcome: string;
  requiredInputs: string[];
  activeDrivers: string[];
  validityLimits: string[];
  supported: boolean;
}

export interface EvaluateRequest {
  request: Request;
  design: Design;
}

export interface BatchEvaluateRequest {
  evaluations: EvaluateRequest[];
}

export interface BatchEvaluateResponse {
  evaluations: Evaluation[];
}

export interface ApplyRequest {
  commands: Command[];
  request: Request;
  design: Design;
}

export interface ApplyResponse {
  applied: string[];
  design: Design;
  evaluation: Evaluation;
}

export interface PreviewRequest {
  command: Command;
  request: Request;
  design: Design;
}

export interface PreviewResponse {
  command: string;
  changes: Change[];
  before: Evaluation;
  after: Evaluation;
}

export interface SweepRequest {
  request: Request;
  settings: SweepSettings;
  design: Design;
}

export interface SweepResponse {
  settingsFingerprint: string;
  snapshot: string;
  solveMode: string;
  detail: string;
  heldFixed: string[];
  alsoChanged: string[];
  bounds: SweepBound[];
  samples: SweepSample[];
  request: Request;
  settings: SweepSettings;
  current: SweepSample;
  invariant: boolean;
}

export interface SweepSettings {
  driver: string;
  output: SweepOutput;
  from: Quantity;
  to: Quantity;
  samples: number;
}

export interface SweepOutput {
  subject: string;
  case?: string;
}

export interface SweepSample {
  value?: Quantity | null;
  trace?: Trace | null;
  status: string;
  feasibility: string;
  detail?: string;
  driver: Quantity;
  hasRequired: boolean;
}

export interface SweepBound {
  name: string;
  direction: string;
  priority: string;
  value: Quantity;
}

export interface PowerSearchRequest {
  request: Request;
  settings: PowerSearchSettings;
  design: Design;
}

export interface PowerSearchResponse {
  settingsFingerprint: string;
  snapshot: string;
  solveMode: string;
  detail: string;
  heldFixed: string[];
  candidates: PowerSearchCandidate[];
  intervals: PowerSearchInterval[];
  request: Request;
  settings: PowerSearchSettings;
  unique: boolean;
  found: boolean;
}

export interface PowerSearchSettings {
  driver: string;
  from: Quantity;
  to: Quantity;
  ceiling: Quantity;
  samples: number;
}

export interface PowerSearchCandidate {
  demand?: Quantity | null;
  status: string;
  feasibility: string;
  detail?: string;
  driver: Quantity;
  margin: number;
  hasRequired: boolean;
  withinCeiling: boolean;
  feasible: boolean;
}

export interface PowerSearchInterval {
  belowFirst?: Quantity | null;
  aboveLast?: Quantity | null;
  detail: string;
  first: Quantity;
  last: Quantity;
  openLow: boolean;
  openHigh: boolean;
}

export interface Evaluation {
  wing?: SolvedWing | null;
  snapshot: string;
  geometry: string;
  aggregate: string;
  powerFeasibility: PowerFeasibility;
  request: Request;
  loads: CaseLoad[];
  definitionIssues: Issue[];
  geometryIssues: Issue[];
  configurationIssues: Issue[];
  conflicts: Conflict[];
  thrustChecks: ThrustCheck[];
  patterns: string[];
  checks: Check[];
  areaUpper: Bound;
  areaLower: Bound;
  electrical: ElectricalBudget;
  massProperties: MassProperties;
  mass: MassRange;
  mission: MissionResult;
  hasRequired: boolean;
}

export interface Design {
  mass?: Quantity | null;
  tail?: Tail | null;
  name: string;
  configuration: string;
  massBasis: string;
  massMode?: string;
  components?: Component[];
  cases?: Case[];
  requirements?: Requirement[];
  polar?: DragPolar | null;
  propulsion?: Propulsion | null;
  battery?: Battery | null;
  auxiliary?: AuxiliaryLoad[];
  mission?: Mission | null;
  wing: Wing;
}

export interface Wing {
  span?: Quantity | null;
  area?: Quantity | null;
  rootChord?: Quantity | null;
  sweep?: Quantity | null;
  dihedral?: Quantity | null;
  twist?: Quantity | null;
  incidence?: Quantity | null;
  bodyWidth?: Quantity | null;
  rootAirfoil?: Airfoil | null;
  tipAirfoil?: Airfoil | null;
  name: string;
  shape: string;
  areaBasis: string;
  dihedralMode?: string;
  aspectRatio: number;
  taperRatio: number;
  sweepReference: number;
}

export interface Airfoil {
  designation: string;
  evidence: string;
  thicknessRatio: number;
}

export interface Tail {
  horizontal?: Surface | null;
  vertical?: Surface | null;
  vtail?: VTail | null;
}

export interface Surface {
  area?: Quantity | null;
  span?: Quantity | null;
  arm?: Quantity | null;
}

export interface VTail {
  panelArea?: Quantity | null;
  panelSpan?: Quantity | null;
  cant?: Quantity | null;
  arm?: Quantity | null;
}

export interface Case {
  name: string;
  configuration: string;
  densityBasis: string;
  viscosityBasis?: string;
  priority: string;
  density?: Quantity | null;
  viscosity?: Quantity | null;
  clmax: CLmax;
  loadFactor: number;
}

export interface CLmax {
  scope: string;
  basis: string;
  evidence?: string;
  max: number;
}

export interface Requirement {
  minimum?: Quantity | null;
  maximum?: Quantity | null;
  name: string;
  subject: string;
  priority: string;
  basis: string;
  cases?: string[];
  margin: number;
}

export interface Command {
  mass?: Quantity | null;
  value?: Quantity | null;
  requirement?: Requirement | null;
  case?: Case | null;
  clmax?: CLmax | null;
  scope?: Scope | null;
  angles?: Angles | null;
  tail?: Tail | null;
  component?: Component | null;
  position?: Position | null;
  polar?: DragPolar | null;
  efficiency?: Efficiency | null;
  limits?: PropulsionLimits | null;
  capability?: Capability | null;
  target?: ThrustTarget | null;
  battery?: Battery | null;
  load?: AuxiliaryLoad | null;
  profile?: MissionProfile | null;
  segment?: MissionSegment | null;
  kind: string;
  basis?: string;
  key?: string;
  promote?: string;
  release?: string;
  name?: string;
  priority?: string;
  hold?: string;
  shape?: string;
  configuration?: string;
  mode?: string;
  ratio?: number;
  index?: number;
}

export interface Scope {
  kind: string;
  case?: string;
}

export interface Angles {
  sweep?: Quantity | null;
  dihedral?: Quantity | null;
  twist?: Quantity | null;
  incidence?: Quantity | null;
  dihedralMode?: string;
  sweepReference: number;
}

export interface Component {
  mass?: Quantity | null;
  position: Position;
  name: string;
  role: string;
  basis: string;
}

export interface Position {
  x?: Quantity | null;
  y?: Quantity | null;
  z?: Quantity | null;
}

export interface MassProperties {
  total?: Quantity | null;
  cg?: Point | null;
  datum: string;
  status: string;
  detail?: string;
  contributions: MassContribution[];
  complete: boolean;
}

export interface MassContribution {
  mass?: Quantity | null;
  position: Position;
  name: string;
  role: string;
  detail?: string;
  moments: Quantity[];
  known: boolean;
}

export interface CaseLoad {
  requiredLift?: Quantity | null;
  case: string;
  priority: string;
  status: string;
  detail?: string;
}

export interface DragPolar {
  cd0Basis: string;
  efficiencyBasis: string;
  configuration: string;
  scope: string;
  evidence?: string;
  cd0: number;
  oswaldEfficiency: number;
  clValidMin: number;
  clValidMax: number;
}

export interface Capability {
  speed?: Quantity | null;
  density?: Quantity | null;
  voltage?: Quantity | null;
  rpm?: Quantity | null;
  thrust?: Quantity | null;
  electricalPower?: Quantity | null;
  current?: Quantity | null;
  name: string;
  basis: string;
  densityBasis?: string;
  note?: string;
  kind: string;
  evidence?: string;
  throttle: number;
}

export interface ThrustTarget {
  name: string;
  basis: string;
  capability: string;
  priority: string;
  ratio: number;
}

export interface PropulsionLimits {
  maxContinuousPower?: Quantity | null;
  maxPeakPower?: Quantity | null;
  maxRpm?: Quantity | null;
  maxVoltage?: Quantity | null;
  propellerDiameter?: Quantity | null;
  propellerHubHeight?: Quantity | null;
  basis?: string;
}

export interface Propulsion {
  limits?: PropulsionLimits | null;
  efficiencyBasis?: string;
  efficiencyEvidence?: string;
  capabilities?: Capability[];
  targets?: ThrustTarget[];
  efficiency: number;
}

export interface Battery {
  capacity?: Quantity | null;
  nominalVoltage?: Quantity | null;
  energy?: Quantity | null;
  continuousCurrentLimit?: Quantity | null;
  peakCurrentLimit?: Quantity | null;
  basis: string;
  component: string;
  mode: string;
  evidence?: string;
  usableFraction: number;
}

export interface AuxiliaryLoad {
  continuous?: Quantity | null;
  peak?: Quantity | null;
  name: string;
  basis: string;
  component?: string;
  side: string;
  evidence?: string;
  regulatorEfficiency: number;
}

export interface MissionSegment {
  speed?: Quantity | null;
  climbAngle?: Quantity | null;
  duration?: Quantity | null;
  distance?: Quantity | null;
  windAlongTrack?: Quantity | null;
  enteredPower?: Quantity | null;
  name: string;
  case: string;
  notes?: string;
  kind: string;
  model: string;
  timing: string;
  enteredBasis?: string;
  enteredEvidence?: string;
  efficiencyBasis?: string;
  capability?: string;
  efficiency: number;
}

export interface Mission {
  name: string;
  basis: string;
  reserveBasis?: string;
  segments?: MissionSegment[];
  reserveFraction: number;
}

export interface Efficiency {
  basis: string;
  evidence?: string;
  total: number;
}

export interface MissionProfile {
  name: string;
  basis: string;
  reserveBasis?: string;
  reserveFraction: number;
}

export interface ElectricalBudget {
  continuous?: Quantity | null;
  peak?: Quantity | null;
  status: string;
  detail?: string;
  evidence?: string;
  loads: AuxiliaryContribution[];
  complete: boolean;
}

export interface AuxiliaryContribution {
  continuous?: Quantity | null;
  peak?: Quantity | null;
  name: string;
  component?: string;
  side: string;
  evidence?: string;
  detail?: string;
  known: boolean;
}

export interface MissionResult {
  requiredEnergy?: Quantity | null;
  usableEnergy?: Quantity | null;
  budget?: Quantity | null;
  totalDuration?: Quantity | null;
  totalDistance?: Quantity | null;
  peakContinuousPower?: Quantity | null;
  status: string;
  energyStatus: string;
  detail?: string;
  segments: SegmentResult[];
  traces: Trace[];
  reserveFraction: number;
  complete: boolean;
}

export interface SegmentResult {
  groundSpeed?: Quantity | null;
  duration?: Quantity | null;
  distance?: Quantity | null;
  energy?: Quantity | null;
  name: string;
  case?: string;
  kind: string;
  status: string;
  detail?: string;
  traces: Trace[];
  availability: SegmentAvailability;
  power: SegmentPower;
}

export interface SegmentPower {
  dynamicPressure?: Quantity | null;
  lift?: Quantity | null;
  drag?: Quantity | null;
  thrust?: Quantity | null;
  propulsive?: Quantity | null;
  propulsiveElectrical?: Quantity | null;
  electrical?: Quantity | null;
  model: string;
  status: string;
  detail?: string;
  evidence?: string;
  traces: Trace[];
  liftCoefficient: number;
  dragCoefficient: number;
  liftToDrag: number;
  chainEfficiency: number;
}

export interface SegmentAvailability {
  availableThrust?: Quantity | null;
  trace?: Trace | null;
  capability?: string;
  detail?: string;
  evidence?: string;
  status: string;
  margin: number;
}

export interface SupplyCheck {
  limit?: Quantity | null;
  actual?: Quantity | null;
  name: string;
  status: string;
  detail?: string;
  margin: number;
}

export interface PowerFeasibility {
  continuousDemand?: Quantity | null;
  peakDemand?: Quantity | null;
  status: string;
  detail?: string;
  peakDetail?: string;
  checks: SupplyCheck[];
}

export interface ThrustCheck {
  trace?: Trace | null;
  name: string;
  capability?: string;
  condition?: string;
  detail?: string;
  priority: string;
  evidence?: string;
  status: string;
  available: number;
  target: number;
  margin: number;
}

export interface SolvedWing {
  datum: string;
  solveMode: string;
  drivers: string[];
  parameters: Parameter[];
  outline: Point[];
  views: SketchView[];
  explanations: Explanation[];
}

export interface Parameter {
  key: string;
  role: string;
  datum?: string;
  equationId?: string;
  revision?: string;
  dependsOn?: string[];
  value: Quantity;
}

export interface Point {
  x: Quantity;
  y: Quantity;
  z: Quantity;
}

export interface SketchView {
  view: string;
  datum: string;
  across: string;
  up: string;
  curves: SketchCurve[];
  dimensions: SketchDimension[];
}

export interface SketchCurve {
  label: string;
  role: string;
  points: Point[];
  mirrored: boolean;
  closed: boolean;
}

export interface SketchDimension {
  key: string;
  label: string;
  detail: string;
  kind: string;
  plane: string;
  from: Point;
  to: Point;
  value: Quantity;
}

export interface Explanation {
  key: string;
  role: string;
  equationId?: string;
  revision?: string;
  expression?: string;
  detail: string;
  substitutions: Substitution[];
  dependsOn: string[];
  value: Quantity;
}

export interface Check {
  name: string;
  case?: string;
  subject: string;
  direction: string;
  priority: string;
  status: string;
  result: string;
  evidence?: string;
  detail?: string;
  actual?: Quantity | null;
  trace?: Trace | null;
  bound: Quantity;
  margin: number;
}

export interface Bound {
  value?: Quantity | null;
  subject: string;
  direction: string;
  detail?: string;
  controlling?: string[];
  contributions?: Contribution[];
  known: boolean;
  partial: boolean;
}

export interface Contribution {
  value?: Quantity | null;
  trace?: Trace | null;
  source: string;
  detail?: string;
  known: boolean;
}

export interface MassRange {
  detail?: string;
  lower: Bound;
  upper: Bound;
  complete: boolean;
  empty: boolean;
}

export interface Conflict {
  summary: string;
  detail: string;
  group: string[];
  alternatives: Alternative[];
}

export interface Alternative {
  name: string;
  description: string;
  command: Command;
}

export interface Change {
  name: string;
  case?: string;
  subject: string;
  direction: string;
  from: string;
  to: string;
  detail: string;
  appeared: boolean;
  vanished: boolean;
}

export interface Trace {
  equationId: string;
  revision: string;
  expression: string;
  substitutions: Substitution[];
  result: Quantity;
}

export interface Substitution {
  name: string;
  value: Quantity;
}

export interface Quantity {
  unit: string;
  value: number;
}

export interface Issue {
  field: string;
  kind: string;
  detail: string;
}

export interface Request {
  session: string;
  sequence: number;
}
