// Code generated by yalb.aero/api. DO NOT EDIT.
//
// Regenerate with: go run ./cmd/aero contract > frontend/src/api/contract.ts
// TestGeneratedTypeScriptMatchesTheCheckedInFile fails when this file drifts
// from the Go types that define the contract.
//
// These are types, not validation. They describe what a response is expected to
// look like and vanish at run time; they do not check that an untrusted body
// has that shape. Validate a decoded response before trusting it.

export const CONTRACT_VERSION = "v1";

export type AreaBasis =
  "reference-trapezoid" |
  "exposed-panels";

export type BoundDirection =
  "minimum" |
  "maximum";

export type CaseScope =
  "all-required" |
  "single";

export type CoefficientScope =
  "aircraft" |
  "airfoil-section";

export type CommandKind =
  "place-component" |
  "promote-driver" |
  "remove-case" |
  "remove-component" |
  "remove-requirement" |
  "set-body-width" |
  "set-case" |
  "set-case-clmax" |
  "set-case-priority" |
  "set-component" |
  "set-configuration" |
  "set-driver" |
  "set-mass" |
  "set-mass-mode" |
  "set-planform-shape" |
  "set-requirement" |
  "set-requirement-priority" |
  "set-taper-ratio" |
  "set-wing-angles" |
  "size-at-stall-limit";

export type ComponentRole =
  "airframe" |
  "battery" |
  "motor" |
  "avionics" |
  "payload" |
  "other";

export type Configuration =
  "conventional-tail" |
  "v-tail" |
  "flying-wing";

export type DihedralMode =
  "hold-panel" |
  "hold-projected";

export type Dimension =
  "ratio" |
  "mass" |
  "force" |
  "length" |
  "area" |
  "speed" |
  "density" |
  "force-per-area" |
  "mass-per-area" |
  "angle" |
  "power" |
  "energy" |
  "dynamic-viscosity" |
  "mass-moment";

export type DimensionKind =
  "linear" |
  "angular";

export type DriverKey =
  "wing.span.projected" |
  "wing.span.panel" |
  "wing.area.reference" |
  "wing.area.panel" |
  "wing.aspect_ratio.planform" |
  "wing.chord.root";

export type Evidence =
  "assumed" |
  "measured" |
  "simulated";

export type IssueKind =
  "missing" |
  "invalid" |
  "unsupported";

export type Journey =
  "span-first" |
  "mass-and-performance-first" |
  "mass-and-size-first" |
  "existing-design" |
  "power-first";

export type MassMode =
  "entered" |
  "components";

export type OutlinePlane =
  "plan-view" |
  "panel-surface";

export type ParameterRole =
  "driver" |
  "derived";

export type PlanformShape =
  "rectangle" |
  "trapezoid";

export type Priority =
  "required" |
  "preferred";

export type RequirementStatus =
  "unknown" |
  "met" |
  "unmet";

export type RequirementSubject =
  "stall-speed" |
  "wing-area" |
  "span" |
  "mass" |
  "aspect-ratio" |
  "mass-wing-loading";

export type ResultStatus =
  "missing" |
  "computed" |
  "invalid" |
  "stale";

export type SketchRole =
  "outline" |
  "centerline" |
  "axis" |
  "construction" |
  "reference";

export type SolveMode =
  "span-and-area" |
  "span-and-aspect-ratio" |
  "area-and-aspect-ratio" |
  "span-and-root-chord" |
  "area-and-root-chord" |
  "aspect-ratio-and-root-chord";

export type SourceKind =
  "book" |
  "supplementary" |
  "derived";

export type SweepDriverKey =
  "design.mass" |
  "wing.span.projected" |
  "wing.span.panel" |
  "wing.area.reference" |
  "wing.area.panel" |
  "wing.aspect_ratio.planform" |
  "wing.chord.root";

export type ViewKind =
  "plan-view" |
  "front-view" |
  "side-view";

export interface Discovery {
  contractVersion: string;
  version: string;
  equations: Equation[];
  patterns: Pattern[];
  units: UnitInfo[];
  vocabularies: Vocabulary[];
  limits: Limits;
}

export interface Limits {
  maxCases: number;
  maxRequirements: number;
  maxCommands: number;
  maxBatch: number;
  maxComponents: number;
  maxSweepSamples: number;
  maxRequestBytes: number;
}

export interface Vocabulary {
  name: string;
  tokens: string[];
}

export interface UnitInfo {
  symbol: string;
  dimension: string;
  factorToSi: number;
  si: boolean;
}

export interface Equation {
  id: string;
  revision: string;
  expression: string;
  source: Source;
  output: Port;
  inputs: Port[];
  assumptions: string[];
}

export interface Port {
  name: string;
  description: string;
  dimension: string;
  unit: string;
}

export interface Source {
  kind: string;
  title: string;
  url: string;
  section: string;
  accessed: string;
  upstreamRevision?: string;
  originalUnits: string;
  adaptation: string;
}

export interface Pattern {
  id: string;
  name: string;
  journey: string;
  rationale: string;
  outcome: string;
  requiredInputs: string[];
  activeDrivers: string[];
  validityLimits: string[];
  supported: boolean;
}

export interface EvaluateRequest {
  request: Request;
  design: Design;
}

export interface BatchEvaluateRequest {
  evaluations: EvaluateRequest[];
}

export interface BatchEvaluateResponse {
  evaluations: Evaluation[];
}

export interface ApplyRequest {
  commands: Command[];
  request: Request;
  design: Design;
}

export interface ApplyResponse {
  applied: string[];
  design: Design;
  evaluation: Evaluation;
}

export interface PreviewRequest {
  command: Command;
  request: Request;
  design: Design;
}

export interface PreviewResponse {
  command: string;
  changes: Change[];
  before: Evaluation;
  after: Evaluation;
}

export interface SweepRequest {
  request: Request;
  settings: SweepSettings;
  design: Design;
}

export interface SweepResponse {
  settingsFingerprint: string;
  snapshot: string;
  solveMode: string;
  detail: string;
  heldFixed: string[];
  alsoChanged: string[];
  bounds: SweepBound[];
  samples: SweepSample[];
  request: Request;
  settings: SweepSettings;
  current: SweepSample;
  invariant: boolean;
}

export interface SweepSettings {
  driver: string;
  output: SweepOutput;
  from: Quantity;
  to: Quantity;
  samples: number;
}

export interface SweepOutput {
  subject: string;
  case?: string;
}

export interface SweepSample {
  value?: Quantity | null;
  trace?: Trace | null;
  status: string;
  feasibility: string;
  detail?: string;
  driver: Quantity;
  hasRequired: boolean;
}

export interface SweepBound {
  name: string;
  direction: string;
  priority: string;
  value: Quantity;
}

export interface Evaluation {
  wing?: SolvedWing | null;
  snapshot: string;
  geometry: string;
  aggregate: string;
  checks: Check[];
  conflicts: Conflict[];
  patterns: string[];
  definitionIssues: Issue[];
  geometryIssues: Issue[];
  configurationIssues: Issue[];
  request: Request;
  areaLower: Bound;
  areaUpper: Bound;
  massProperties: MassProperties;
  loads: CaseLoad[];
  mass: MassRange;
  hasRequired: boolean;
}

export interface Design {
  mass?: Quantity | null;
  tail?: Tail | null;
  name: string;
  configuration: string;
  massBasis: string;
  massMode?: string;
  components?: Component[];
  cases?: Case[];
  requirements?: Requirement[];
  wing: Wing;
}

export interface Wing {
  span?: Quantity | null;
  area?: Quantity | null;
  rootChord?: Quantity | null;
  sweep?: Quantity | null;
  dihedral?: Quantity | null;
  twist?: Quantity | null;
  incidence?: Quantity | null;
  bodyWidth?: Quantity | null;
  rootAirfoil?: Airfoil | null;
  tipAirfoil?: Airfoil | null;
  name: string;
  shape: string;
  areaBasis: string;
  dihedralMode?: string;
  aspectRatio: number;
  taperRatio: number;
  sweepReference: number;
}

export interface Airfoil {
  designation: string;
  evidence: string;
  thicknessRatio: number;
}

export interface Tail {
  horizontal?: Surface | null;
  vertical?: Surface | null;
  vtail?: VTail | null;
}

export interface Surface {
  area?: Quantity | null;
  span?: Quantity | null;
  arm?: Quantity | null;
}

export interface VTail {
  panelArea?: Quantity | null;
  panelSpan?: Quantity | null;
  cant?: Quantity | null;
  arm?: Quantity | null;
}

export interface Case {
  name: string;
  configuration: string;
  densityBasis: string;
  viscosityBasis?: string;
  priority: string;
  density?: Quantity | null;
  viscosity?: Quantity | null;
  clmax: CLmax;
  loadFactor: number;
}

export interface CLmax {
  scope: string;
  basis: string;
  evidence?: string;
  max: number;
}

export interface Requirement {
  minimum?: Quantity | null;
  maximum?: Quantity | null;
  name: string;
  subject: string;
  priority: string;
  basis: string;
  cases?: string[];
  margin: number;
}

export interface Command {
  mass?: Quantity | null;
  value?: Quantity | null;
  requirement?: Requirement | null;
  case?: Case | null;
  clmax?: CLmax | null;
  scope?: Scope | null;
  angles?: Angles | null;
  tail?: Tail | null;
  component?: Component | null;
  position?: Position | null;
  kind: string;
  basis?: string;
  key?: string;
  promote?: string;
  release?: string;
  name?: string;
  priority?: string;
  hold?: string;
  shape?: string;
  configuration?: string;
  mode?: string;
  ratio?: number;
}

export interface Scope {
  kind: string;
  case?: string;
}

export interface Angles {
  sweep?: Quantity | null;
  dihedral?: Quantity | null;
  twist?: Quantity | null;
  incidence?: Quantity | null;
  dihedralMode?: string;
  sweepReference: number;
}

export interface Component {
  mass?: Quantity | null;
  position: Position;
  name: string;
  role: string;
  basis: string;
}

export interface Position {
  x?: Quantity | null;
  y?: Quantity | null;
  z?: Quantity | null;
}

export interface MassProperties {
  total?: Quantity | null;
  cg?: Point | null;
  datum: string;
  status: string;
  detail?: string;
  contributions: MassContribution[];
  complete: boolean;
}

export interface MassContribution {
  mass?: Quantity | null;
  position: Position;
  name: string;
  role: string;
  detail?: string;
  moments: Quantity[];
  known: boolean;
}

export interface CaseLoad {
  requiredLift?: Quantity | null;
  case: string;
  priority: string;
  status: string;
  detail?: string;
}

export interface SolvedWing {
  datum: string;
  solveMode: string;
  drivers: string[];
  parameters: Parameter[];
  outline: Point[];
  views: SketchView[];
  explanations: Explanation[];
}

export interface Parameter {
  key: string;
  role: string;
  datum?: string;
  equationId?: string;
  revision?: string;
  dependsOn?: string[];
  value: Quantity;
}

export interface Point {
  x: Quantity;
  y: Quantity;
  z: Quantity;
}

export interface SketchView {
  view: string;
  datum: string;
  across: string;
  up: string;
  curves: SketchCurve[];
  dimensions: SketchDimension[];
}

export interface SketchCurve {
  label: string;
  role: string;
  points: Point[];
  mirrored: boolean;
  closed: boolean;
}

export interface SketchDimension {
  key: string;
  label: string;
  detail: string;
  kind: string;
  plane: string;
  from: Point;
  to: Point;
  value: Quantity;
}

export interface Explanation {
  key: string;
  role: string;
  equationId?: string;
  revision?: string;
  expression?: string;
  detail: string;
  substitutions: Substitution[];
  dependsOn: string[];
  value: Quantity;
}

export interface Check {
  name: string;
  case?: string;
  subject: string;
  direction: string;
  priority: string;
  status: string;
  result: string;
  evidence?: string;
  detail?: string;
  actual?: Quantity | null;
  trace?: Trace | null;
  bound: Quantity;
  margin: number;
}

export interface Bound {
  value?: Quantity | null;
  subject: string;
  direction: string;
  detail?: string;
  controlling?: string[];
  contributions?: Contribution[];
  known: boolean;
  partial: boolean;
}

export interface Contribution {
  value?: Quantity | null;
  trace?: Trace | null;
  source: string;
  detail?: string;
  known: boolean;
}

export interface MassRange {
  detail?: string;
  lower: Bound;
  upper: Bound;
  complete: boolean;
  empty: boolean;
}

export interface Conflict {
  summary: string;
  detail: string;
  group: string[];
  alternatives: Alternative[];
}

export interface Alternative {
  name: string;
  description: string;
  command: Command;
}

export interface Change {
  name: string;
  case?: string;
  subject: string;
  direction: string;
  from: string;
  to: string;
  detail: string;
  appeared: boolean;
  vanished: boolean;
}

export interface Trace {
  equationId: string;
  revision: string;
  expression: string;
  substitutions: Substitution[];
  result: Quantity;
}

export interface Substitution {
  name: string;
  value: Quantity;
}

export interface Quantity {
  unit: string;
  value: number;
}

export interface Issue {
  field: string;
  kind: string;
  detail: string;
}

export interface Request {
  session: string;
  sequence: number;
}
