package api

import (
	"reflect"
	"strings"
)

// The Go types in this package are the single contract authority. The
// TypeScript a frontend compiles against is generated from them by
// TypeScript(), and TestGeneratedTypeScriptMatchesTheCheckedInFile fails when
// the checked-in file drifts, so the two cannot disagree quietly.
//
// Types alone are not validation. A TypeScript interface describes what a
// response is expected to look like and disappears at run time; it does not
// check that an untrusted body actually has that shape. The generated file says
// so at the top, and a client that parses a response still has to validate it.

// tsRoots are the types the generated module exports, in the order they appear.
// Nested types are discovered from these, so adding a field of a new struct type
// is enough to publish it.
var tsRoots = []any{
	Discovery{}, Limits{}, Vocabulary{}, UnitInfo{}, Equation{}, Port{}, Source{}, Pattern{},
	EvaluateRequest{}, BatchEvaluateRequest{}, BatchEvaluateResponse{},
	ApplyRequest{}, ApplyResponse{}, PreviewRequest{}, PreviewResponse{},
	SweepRequest{}, SweepResponse{}, SweepSettings{}, SweepOutput{}, SweepSample{}, SweepBound{},
	Evaluation{}, Design{}, Wing{}, Airfoil{}, Tail{}, Surface{}, VTail{},
	Case{}, CLmax{}, Requirement{}, Command{}, Scope{}, Angles{},
	Component{}, Position{}, MassProperties{}, MassContribution{}, CaseLoad{},
	SolvedWing{}, Parameter{}, Point{}, SketchView{}, SketchCurve{}, SketchDimension{}, Explanation{},
	Check{}, Bound{}, Contribution{},
	MassRange{}, Conflict{}, Alternative{}, Change{}, Trace{}, Substitution{},
	Quantity{}, Issue{}, Request{},
}

// TypeScript renders the wire contract as a TypeScript module. It is
// deterministic: the same package produces the same bytes, which is what lets a
// test compare it against the checked-in file.
func TypeScript() string {
	var out strings.Builder
	out.WriteString(tsHeader)
	out.WriteString("\nexport const CONTRACT_VERSION = " + quoteTS(ContractVersion) + ";\n")
	out.WriteString(tsVocabularies())
	seen := make(map[string]bool, len(tsRoots))
	for _, root := range tsRoots {
		t := reflect.TypeOf(root)
		if seen[t.Name()] {
			continue
		}
		seen[t.Name()] = true
		out.WriteString("\n" + tsInterface(t))
	}
	return out.String()
}

const tsHeader = `// Code generated by yalb.aero/api. DO NOT EDIT.
//
// Regenerate with: go run ./cmd/aero contract > frontend/src/api/contract.ts
// TestGeneratedTypeScriptMatchesTheCheckedInFile fails when this file drifts
// from the Go types that define the contract.
//
// These are types, not validation. They describe what a response is expected to
// look like and vanish at run time; they do not check that an untrusted body
// has that shape. Validate a decoded response before trusting it.
`

// tsVocabularies emits the enum tokens as string-literal unions, so a client
// that mistypes a token fails to compile rather than at the boundary.
func tsVocabularies() string {
	var out strings.Builder
	for _, vocabulary := range Vocabularies() {
		name := strings.ToUpper(vocabulary.Name[:1]) + vocabulary.Name[1:]
		lines := make([]string, 0, len(vocabulary.Tokens))
		for _, token := range vocabulary.Tokens {
			lines = append(lines, "  "+quoteTS(token))
		}
		out.WriteString("\nexport type " + name + " =\n" + strings.Join(lines, " |\n") + ";\n")
	}
	return out.String()
}

// tsInterface renders one struct as an interface, using the JSON field names
// and marking an omitempty field optional.
func tsInterface(t reflect.Type) string {
	var out strings.Builder
	out.WriteString("export interface " + t.Name() + " {\n")
	for n := range t.NumField() {
		field := t.Field(n)
		name, optional, skip := jsonField(field)
		if skip {
			continue
		}
		question := ""
		if optional {
			question = "?"
		}
		out.WriteString("  " + name + question + ": " + tsType(field.Type) + ";\n")
	}
	out.WriteString("}\n")
	return out.String()
}

// jsonField reads a field's JSON name and whether it may be absent.
func jsonField(field reflect.StructField) (name string, optional, skip bool) {
	tag := field.Tag.Get("json")
	if tag == "-" || !field.IsExported() {
		return "", false, true
	}
	name, rest, _ := strings.Cut(tag, ",")
	if name == "" {
		name = field.Name
	}
	optional = strings.Contains(rest, "omitempty") || field.Type.Kind() == reflect.Pointer
	return name, optional, false
}

// tsType maps a Go type onto its TypeScript form. Only the kinds the contract
// actually uses are handled; anything else becomes "unknown", which fails to
// compile at the use site rather than silently widening the contract.
func tsType(t reflect.Type) string {
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Float64, reflect.Int, reflect.Uint64:
		return "number"
	case reflect.Pointer:
		return tsType(t.Elem()) + " | null"
	case reflect.Slice:
		return tsType(t.Elem()) + "[]"
	case reflect.Struct:
		return t.Name()
	default:
		return "unknown"
	}
}

func quoteTS(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}
